[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin.objc]
rustc-link-lib = []

[target.x86_64-apple-darwin.objc]
rustc-link-lib = []

# Override for the host build script (always compiles as x86_64-unknown-linux-gnu):
[target.x86_64-unknown-linux-gnu.objc]
rustc-link-lib = []

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
